
package net.atos.weatherapplication.soap;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "GetTownWeatherRequestFault", targetNamespace = "http://www.example.org/WeatherAPI/")
public class GetTownWeatherRequestFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GetTownWeatherRequestFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public GetTownWeatherRequestFaultMessage(String message, GetTownWeatherRequestFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public GetTownWeatherRequestFaultMessage(String message, GetTownWeatherRequestFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: net.atos.weatherapplication.soap.GetTownWeatherRequestFault
     */
    public GetTownWeatherRequestFault getFaultInfo() {
        return faultInfo;
    }

}
